blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/w111/AI-Pages/discussions
    about: Общие обсуждения и идеи для проекта
  - name: 📚 Документация
    url: https://github.com/w111/AI-Pages/blob/main/README.md
    about: Официальная документация проекта
  - name: 🚀 Демо
    url: https://w111.github.io/AI-Pages/
    about: Живая демонстрация всех игр и приложений