name: ❓ Вопрос
description: Задать вопрос о проекте
title: "[ВОПРОС]: "
labels: ["question", "needs-answer"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за ваш вопрос! Пожалуйста, заполните форму ниже.

  - type: textarea
    id: question
    attributes:
      label: ❓ Ваш вопрос
      description: Четко сформулируйте ваш вопрос.
      placeholder: Опишите ваш вопрос...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 📂 Категория вопроса
      description: К какой области относится ваш вопрос?
      options:
        - 🚀 Начало работы
        - 💻 Разработка
        - 🎮 Использование игр/приложений
        - 🔧 Техническая поддержка
        - 📚 Документация
        - 🤝 Участие в проекте
        - 🌐 Развертывание
        - 🔒 Безопасность
        - Другое
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🔍 Контекст
      description: Предоставьте любую дополнительную информацию, которая может помочь понять ваш вопрос.
      placeholder: |
        - Что вы пытаетесь сделать?
        - Какую документацию вы уже читали?
        - Какие шаги вы уже предприняли?

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Среда (если применимо)
      description: Информация о вашей среде разработки или системе.
      placeholder: |
        - ОС: [например, macOS, Windows, Linux]
        - Браузер: [например, Chrome 91, Firefox 89]
        - Node.js версия: [например, 16.14.0]
        - Другие релевантные детали...
