name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  claude-assistant:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.pull_request.body, '@claude')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

      - name: Process request
        run: |
          claude-code process \
            --context "${{ github.event_name }}" \
            --repository "${{ github.repository }}" \
            --issue-number "${{ github.event.issue.number || github.event.pull_request.number }}" \
            --comment-body "${{ github.event.comment.body || github.event.issue.body || github.event.pull_request.body }}"

      - name: Post response
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = process.env.CLAUDE_RESPONSE;
            if (response) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: response
              });
            }
